### ISSUE TITLE
How to check secret validity 

### ISSUE THREAD

**Issue by khaliddd** [sbertix/Swiftagram#103]
Hello, 

how can I check if secret stored in keychain is not expired or its still valid ?

**Comment by sbertix** [comment]
Hey @khaliddd,
Instagram authentication cookies never actually expire: they timeout client side but they're still just as valid for requesting. 
So the approach for dealing with `Secret`'s invalidation should always be "try fetching your request" and be ready to deal with failures, instead of directly questioning whether your `Secret` is still valid or not 😊 
Hope it helps.
