### ISSUE TITLE
Matching feature not working?

### ISSUE THREAD

**Issue by eak65** [sbertix/Swiftagram#293]
Hi, This library seems to be well written Great job @sbertix. I am trying to see if a user followers another user.

```
Endpoint.user(identifier)
                .following(matching: username)
                .unlock(with: secret)
                .session(.instagram)
                .pages(1, delay: 1)  
                .sink(receiveCompletion: { _ in
                    
                }, receiveValue: {
                    print($0) })
                .store(in: &bin)
```
I expected this to return the "username" profile if the "identifier" user is following the "username". This does not happen. It returns the first page of the "identifiers" following page... How can we check if two users follower each other

**Comment by sbertix** [comment]
Hey @eak65,

Thank you :blush: and sorry for the late reply. 

If one of the two profiles corresponds to the logged in user you could do `Endpoint.Friendship.summary(for:)`, passing the identifier of the other one. 

Otherwise, there's not a "quick" way to check for "following" status between two users when one of them is not the logged in account, because of API limitations. Your best bet is fetching all followers/following and go with that. 
The `query` you pass with `matching` should indeed filter followers/following like in the app, but it appears to now be broken, somehow. I'll try and fix it for `6.0.0`. 

_Also, please make sure to use the **Discussions** page of the repo next time you're looking for help._
