### ISSUE TITLE
Followers example crushing

### ISSUE THREAD

**Issue by sbertix** [sbertix/Swiftagram#31]
@sbertix I just tried to run the Followers example on the SE 2 simulator. It launch but when I login with correct credentials it crash :/

_Originally posted by @vlourme in https://github.com/TheM4hd1/SwiftyInsta/issues/195#issuecomment-647630949_

**Comment by sbertix** [comment]
I can't seem to replicate it 🤔 
Any additional info? @vlourme

**Comment by vlourme** [comment]
I'll try to provide some logs or something to help, please wait 👍

**Comment by vlourme** [comment]
So, here is what I am getting :
- When testing on simulators (tested on both SE 2 and iPhone 11), when I type using hardware keyboard (MacOS keyboard), it just fails to Error 5, looks like bad credentials (but I'm sure credentials are valid).
- But when I type using software keyboard from the simulator, it crash while signing in without any log detail.

This could be Xcode or Simulator errors, but seems I can't install the app on my own device because of some developer permissions 
<img width="839" alt="Capture d’écran 2020-06-23 à 10 31 48" src="https://user-images.githubusercontent.com/58728578/85380051-c0785c00-b53c-11ea-8473-c6a59dcf5524.png">


Software keyboard error:
<img width="1439" alt="Capture d’écran 2020-06-22 à 18 39 45" src="https://user-images.githubusercontent.com/58728578/85379850-860ebf00-b53c-11ea-950c-b6881d6912b8.png">

Hardware keyboard error:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-06-22 at 18 38 50](https://user-images.githubusercontent.com/58728578/85379864-88711900-b53c-11ea-8687-9b500c4a829a.png)

**Comment by sbertix** [comment]
You need to select your account from `Xcode` project settings, or just set it to `None`.\
It's not an issue with **Swiftagram** per se.\
I'll update it so it uses `None` by default.
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/1803415/85383293-14d10b00-b540-11ea-99f5-f5e3a8774a7b.png">

I'm releasing `2.1` in a couple of hours, so I would just hold on until then and check it out once it's updated 😊
