### ISSUE TITLE
Followers / Following endpoint error 

### ISSUE THREAD

**Issue by aslios** [sbertix/Swiftagram#46]
Hi Sbertix,
I so much business ur api nowadays :) but i have problem please help me.I created a algorithm for find my lost followers and gained followers.Because of this i get my followers and my following  via ur api and compare.. But when i try to get my followers or following **( _Endpoint.Friendship.followed(by: secret.identifier) run this code 2-3 time_  )**    i get this error => **"Please wait a few minutes before you try again.."** and my code is not working :( I know this error due to instagram filters.But there are too much application in app store do this same algorithm succesfuly without error.How can they do this? how can i pass this error? sometimes i run this code first time and i get this error.How can i get my lost followers and gaind followers without error?

**Comment by sbertix** [comment]
It's mostly about timing, you just need to wait longer before pagination requests.\
That's the only trick. 

Most apps on the App Store actually scrape the followers page, instead of using the private API, which doesn't appear to have the same rate limits.

Unfortunately followers/following endpoints are extremely restricted, and you might trigger that same error even just manually checking your Instagram app.

Not much I can do to help unfortunately.

**Comment by igornazarov1991** [comment]
@sbertix , when you say that most apps actually use wed page scraping of the followers page, do you mean extracting followers from the HTML content? If I understand correctly, it is needed to simulate "scrolling" of the page for downloading next portions of data, right?
